http_server:
  port: 5000

logging:
  level: info
  use_color: true

# If you are in the same broadcast domain, then
# it's easier to just use the broadcast address of your network
discovery_ips:
  - 192.168.1.255
